HosMan/main/default/objects/New_Patient__c/New_Patient__c.object-meta.xml
<CustomObject>
    <label>New Patient</label>
    <nameField>
        <displayFormat>H-{000}</displayFormat>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HosMan/main/default/objects/New_Patient__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

HosMan/main/default/objects/New_Patient__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

HosMan/main/default/objects/New_Patient__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HosMan/main/default/classes/HospitalMangaementClass.cls
public with sharing class HospitalMangaementClass {
    public  List<New_Patient__c> acc  {get;set;}
 
   public String searchKey {get;set;}
    private integer offsetSize=0;
    private integer limitSize=10;
    public  List<string> ids{set;get;}
    public string recID {set;get;}
    public PageReference flowPage{set;get;}
    public HospitalMangaementClass() {
        acc = new List<New_Patient__c>();
       acc=  Database.query('select id,Name,Name1__c,Sex__c,Date_Time__c,Email_ID__c,Mobile_No__c from New_Patient__c    ORDER BY name ASC  Limit '+limitSize+' Offset '+offsetSize   );
       
    }
    
     public  void  search(){
        
       string searchquery='select id,Name,Name1__c,Sex__c,Date_Time__c,Email_ID__c,Mobile_No__c from New_Patient__c where Name1__c like \'%'+searchKey+'%\' ORDER BY name ASC Limit '+limitSize+' Offset '+offsetSize;
       acc= Database.query(searchquery);
          
       
       if(searchKey == null){
           acc= Database.query('select id,Name,Name1__c,Sex__c,Date_Time__c,Email_ID__c,Mobile_No__c from New_Patient__c ORDER BY name ASC  Limit '+limitSize+' Offset '+offsetSize );
       }
         
    }

    
    public void clear(){
        acc.clear();
     searchKey = null;
        acc=  Database.query('select id,Name,Name1__c,Sex__c,Date_Time__c,Email_ID__c,Mobile_No__c from New_Patient__c ORDER BY name ASC   Limit '+limitSize+' Offset '+offsetSize );
        acc.clear();
        acc=  Database.query('select id,Name,Name1__c,Sex__c,Date_Time__c,Email_ID__c,Mobile_No__c from New_Patient__c ORDER BY name ASC   Limit '+limitSize+' Offset '+offsetSize );
    }
    public void previous()
    {
        offsetSize = offsetSize - limitSize;
        search();
        clear();
    }
    public void next(){
        OffsetSize= offsetSize + limitSize;
        search();
        clear();
    }
    public Boolean gethasPrevious()
{
  return (offsetSize > 0);
}
      public Boolean gethasNext()
{
    if (acc.size() < offsetSize){
        return false; 
    }
   
    else{
       return true;
    }
}
    public pagereference GotoFlow( ){
       
          //String urlParams = '?RecordId=' + string.join(FulfillmentOrdersId(acc), '&ids=');
       PageReference flowPage =  new PageReference('/flow/HospitalFlow?RecordId=');
         //  flowPage.getParameters()                                 
       flowPage.setRedirect(true);
       return flowPage;
    }
   public List<String> FulfillmentOrdersId(List<New_Patient__c> acc) {
      
         ids = new List<string>();

          for (New_Patient__c record : acc) {
              ids.add(record.Id);
                 }
        return ids;
    }
   
}